export const GET_MEALS = 'GET_MEALS';
export const GET_MEAL = 'GET_MEAL';
export const SEARCH_MEAL = 'SEARCH_MEAL';
export const SET_MEALS = 'SET_MEALS';
export const SHOW_ALERT = 'SHOW_ALERT';
export const MEAL_MODAL = ' MEAL_MODAL';
export const BAD_SEARCH = 'BAD_SEARCH';
export const NEXT_PAGE = 'NEXT_PAGE';
export const SET_LOADING = 'SET_LOADING';
export const FAVED = 'FAVED';
export const SEARCH_ERROR = 'SEARCH_ERROR'
export const GET_FAVS = 'GET_FAVS';
export const BLANK_SEARCH = 'BLANK_SEARCH';